DROP TABLE IF EXISTS CUSTOMER;
DROP SEQUENCE IF EXISTS SEQ_CUSTOMER;

CREATE TABLE CUSTOMER
(ID INT PRIMARY KEY,
   USERNAME VARCHAR(255) not null,
  PASSWORD VARCHAR(255) NOT NULL,
   FIRSTNAME VARCHAR(255) NOT NULL,
  LASTNAME VARCHAR(255) NOT NULL
);
CREATE SEQUENCE SEQ_CUSTOMER; 

DROP TABLE ADDRESS;
DROP SEQUENCE IF EXISTS SEQ_ADDRESS;

CREATE TABLE ADDRESS
(ID INT PRIMARY KEY,
   ADDRESS1 VARCHAR(255) NOT NULL,
  ADDRESS2 VARCHAR(255),
   ADDRESS3 VARCHAR(255),
  CITY VARCHAR(255) NOT NULL,
  STATE VARCHAR(255) NOT NULL,
  CUSTOMER_ID INT
);
CREATE SEQUENCE SEQ_ADDRESS;

DROP TABLE PRODUCT;
DROP SEQUENCE IF EXISTS SEQ_PRODUCT;

CREATE TABLE PRODUCT (
	ID INT PRIMARY KEY,
	NAME VARCHAR(255) NOT NULL,
	DESCRIPTION VARCHAR(255) NOT NULL,
	PRICE DECIMAL(10, 2)
);
CREATE SEQUENCE SEQ_PRODUCT;

DROP TABLE ORDERS;
DROP SEQUENCE IF EXISTS SEQ_ORDERS;

CREATE TABLE ORDERS (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  customer_id INT,
  product_id INT,
  quantity INT
);
 
CREATE SEQUENCE SEQ_ORDERS;

